name: Cleanup All Workflow Runs

on:
  workflow_dispatch: # 允許在 GitHub Actions 頁面手動點擊按鈕一鍵執行

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    steps:
      - name: Delete all workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 0
